### ISSUE TITLE
This is a not issues just a question

### ISSUE THREAD

**Issue by sertunc** [mbrimble/biztalkdocumenter#15]
Hello, I am sertunc and i am beginner biz talk. i just want to learn, can i get availability or health info from RestApi.

thank you

**Comment by Dijkgraaf** [comment]
Hi Sertunc

BizTalk Documenter doesn't look at the health information of BizTalk, it just documents BizTalk applications.  If you want to check the health of BizTalk you should look at [BizTalk Health Monitor](https://www.microsoft.com/en-nz/download/details.aspx?id=43716) from Microsoft or if you want active monitoring you want to look at a third party product such as [BizTalk360](https://www.biztalk360.com/)

**Comment by sertunc** [comment]
Thank you for your answer, so biztalk health monitor has a any rest api ?

**Comment by Dijkgraaf** [comment]
No, BizTalk Health Monitor does not have an rest APIs so far as I'm aware, BizTalk360 however does.  BHM is free, BizTalk360 you need to pay licencing for.
